config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup'    => 'users#new'
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy' 

  namespace :admin do
    resources :categories do
      resources :words
    end
  end
  resources :categories, only: [:index]
  resources :lessons do
    resources :lesson_words, path: "words", as: "words" #pathで指定した名前をlesson_wordsの代わりに利用できる #
  end
  resources :relationships, only: [:create, :destroy]
  resources :users, except: :new do
    member do  #memberメソッドを使うとユーザーidがURLに含まれるように扱う
      get :following, :followers #/users/:id/followers(.:format)
    end
    resources :words
    resources :categories do
      resources :words
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
        @lessons = Lesson.where(user_id: current_user.id)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            <section class="stats">
                <%= render 'shared/stats' %>
            </section>
        </aside>
        <div class="col-md-8">
                <div class="btn-bigger">
                    <%= link_to "Words", user_words_path(current_user) , class: "btn btn-primary btn-lg" %>
                    <%= link_to "Lesson", categories_path , class: "btn btn-primary btn-lg" %>
                </div>
                <section class="activities">
                    <h3>Activities</h3>
                </section>
                <% @lessons.each do |lesson| %>
                    <span class="category-home">
                        <ul>
                            <li>
                                <% if lesson.category.picture? %>
                                    <%= image_tag category.picture.url %>
                                <% else %>
                                    <img src="/user_default_picture/default_setting.png" alt="default-avatar">
                                <% end %>

                                <span>learned: <%= pluralize(lesson.lesson_words.count, "word")%> in Lesson "<%= lesson.category.title %>"</span>
                            </li>
                        </ul>
                    </span>
                <% end %>


    <!--                     <%# lesson.words.each do |word| %>
                    <tr>
                            <td><%#= word.content %></td>
                            <td><%#= word.correct_answer.content %></td>
                    </tr>
 -->
        </div>
    </div>
<% else %>
    <div class="jumbotron">

        <div id="greeting">
            <h1 class="text-center">Welcome to</h1>
            <h1 class="text-center">E-Learning System</h1>
        </div>

        <div id="signup-btn">
            <%= link_to "Sign up", signup_path , class: "btn btn-primary center-block" %>
        </div>

    </div>
<% end %>