config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup'    => 'users#new'
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy' 

  namespace :admin do
    resources :categories do
      resources :words
    end
  end
  resources :categories, only: [:index]
  resources :lessons do
    resources :lesson_words, path: "words", as: "words" #pathで指定した名前をlesson_wordsの代わりに利用できる #
  end
  resources :relationships, only: [:create, :destroy]
  resources :users, except: :new do
    member do  #memberメソッドを使うとユーザーidがURLに含まれるように扱う
      get :following, :followers #/users/:id/followers(.:format)
    end
    resources :words
    resources :categories do
      resources :words
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :words, dependent: :destroy
    has_many :lessons, dependent: :destroy
    has_many :users, through: :lessons
    mount_uploader :picture, CategoryPictureUploader
    validates :title, presence: true, length: {minimum: 5}
    validates :description, presence: true, length: {minimum: 10}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new

  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_url
    else
      render "new"
    end
  end

  def edit

  end

  private
  def category_params
    params.require(:category).permit(:title, :description, :picture)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.paginate(page: params[:page])
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li>
    <div class=“row”>
        <div class="col-md-6">
            <div class="title"><h1><%= category.title %></h1></div>
            <div class="description"><%= category.description %></div>
            <% if category.lessons.where(user_id: current_user.id).any? %>
                <div>
                    <%= link_to "Already Done", lesson_path(id: category.id),
                                                class: "btn btn-default btn-lg" %>
                </div>
            <% else %>
                <div>
                    <%= link_to "Lesson Start", lessons_path(category_id: category.id),
                                                class: "btn btn-primary btn-lg",
                                                method: :post %>
                </div>
            <% end %>
        </div>
        <div class="col-md-6">
            <div class="category-picture">
                <% if category.picture? %>
                    <%= image_tag category.picture.url %>
                <% else %>
                    <img src="/user_default_picture/default_setting.png" alt="default-avatar">
                <% end %>
            </div>
        </div>
    </div>
</li>

app/views/categories/index.html.erb
<%= will_paginate %>
    <ul>
        <%= render @categories %>
        <!-- 上がeach doをやった上にcategoryにしている -->
    </ul>