config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup'    => 'users#new'
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy' 

  namespace :admin do
    resources :categories do
      resources :words
    end
  end
  resources :categories, only: [:index]
  resources :lessons do
    resources :lesson_words, path: "words", as: "words" #pathで指定した名前をlesson_wordsの代わりに利用できる #
  end
  resources :relationships, only: [:create, :destroy]
  resources :users, except: :new do
    member do  #memberメソッドを使うとユーザーidがURLに含まれるように扱う
      get :following, :followers #/users/:id/followers(.:format)
    end
    resources :words
    resources :categories do
      resources :words
    end
  end

end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
        <div class="container">
            <%= link_to "E-Learning System", root_path, class: "navbar-brand" %>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Profile", user_path(current_user) %></li> 
                          <!-- user_path(current_user)は current_userだけでもok -->
                          <li><%= link_to "Edit My Profile", edit_user_path(current_user) %></li>
                          <% if current_user.admin? %>
                            <li><%= link_to "Manage Categories", admin_categories_path %></li>
                          <% end %>
                          <li class="divider"></li>
                          <li>
                            <%= link_to "Log out", logout_path, method: :delete %>
                          </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>RorElearning</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render "layouts/header" %>
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <div class="container">
            <%= yield %>
        </div>
    </body>
</html>



<!-- パーシャルファイルについて -->
<!--   著者は、複数のビューで共有するユーティリティパーシャルについてはsharedフォルダに保存し、文字どおり全ページ (サイトレイアウトの一部として) 共通のパーシャルについてはlayoutsディレクトリへ保存することを好んでいます (sharedディレクトリは第7章で作成します)。著者はこのように分割保存するのが論理的であると考えますが、sharedフォルダにすべて保存しても問題なく動作します。 ↑ -->